#!/usr/bin/env python3
"""One-time download of the site's fonts from Google Fonts.

Writes site/assets/fonts/*.woff2 (latin + latin-ext subsets), the licence files,
and site/assets/css/fonts.css with local URLs. Run from anywhere:
    python3 scripts/fetch-fonts.py
"""
import pathlib
import re
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[1]
FONTS = ROOT / "site/assets/fonts"
CSS = ROOT / "site/assets/css/fonts.css"
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0 Safari/537.36")
FAMILIES = ["Instrument+Serif:ital@0;1", "IBM+Plex+Sans:wght@400;500;600"]
SUBSETS = {"latin", "latin-ext"}
LICENSES = {
    "LICENSE-instrument-serif.txt": "https://raw.githubusercontent.com/Instrument/instrument-serif/main/OFL.txt",
    "LICENSE-ibm-plex.txt": "https://raw.githubusercontent.com/IBM/plex/master/LICENSE.txt",
}
BLOCK = re.compile(r"/\* ([a-z-]+) \*/\s*(@font-face \{.*?\})", re.S)


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req) as r:
        return r.read()


def main() -> None:
    FONTS.mkdir(parents=True, exist_ok=True)
    CSS.parent.mkdir(parents=True, exist_ok=True)
    # Google serves one variable-font file for every requested weight of a variable
    # family, so group the @font-face blocks by file and declare a weight range once.
    faces: dict[tuple, dict] = {}
    for fam in FAMILIES:
        css = get(f"https://fonts.googleapis.com/css2?family={fam}&display=swap").decode()
        for subset, block in BLOCK.findall(css):
            if subset not in SUBSETS:
                continue
            family = re.search(r"font-family: '([^']+)'", block).group(1)
            style = re.search(r"font-style: (\w+)", block).group(1)
            weight = int(re.search(r"font-weight: (\d+)", block).group(1))
            url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
            face = faces.setdefault((family, style, subset, url), {"block": block, "weights": []})
            face["weights"].append(weight)
    out = ["/* Generated by scripts/fetch-fonts.py. Do not edit by hand. Licences sit next to the font files. */"]
    for (family, style, subset, url), face in faces.items():
        weights = sorted(face["weights"])
        slug = family.lower().replace(" ", "-")
        label = f"{weights[0]}" if len(weights) == 1 else f"{weights[0]}-{weights[-1]}"
        name = f"{slug}-{label}-{style}-{subset}.woff2"
        (FONTS / name).write_bytes(get(url))
        block = face["block"].replace(url, f"../fonts/{name}")
        block = re.sub(r"font-weight: \d+;", f"font-weight: {label.replace('-', ' ')};", block)
        out.append(f"/* {subset} */\n{block}")
    for name, url in LICENSES.items():
        (FONTS / name).write_bytes(get(url))
    CSS.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {CSS.relative_to(ROOT)} and {len(faces)} woff2 files")


if __name__ == "__main__":
    main()
